development:
  password: b6dc82cb6bbb11da4eaa4a666fefaf2d
  theme_id: "16646373437"
  store: rebel-beaches.myshopify.com
production:
  password: b6dc82cb6bbb11da4eaa4a666fefaf2d
  theme_id: "live"
  store: rebel-beaches.myshopify.com
